### ISSUE TITLE
s63file.cpp/.h is disappeared.

### ISSUE THREAD

**Issue by dnwkfkwk** [pavelpasha/s63lib#5]
Thank you for your great work.

I tried to compile at vs2017. But s63file.cpp and s63file.h files are not included in Code..

Please answer me..

**Comment by pavelpasha** [comment]
I removed the S63Class from the project (it was just an abstraction of byte array), but it was still exist in the .vcxproj file. So i removed it from anywhere with last commit. Now the project should compile.

**Comment by pavelpasha** [comment]
Tell if all ok.

**Comment by dnwkfkwk** [comment]
Thank you for your answer!
This project work well now!
