### ISSUE TITLE
Many errors 

### ISSUE THREAD

**Issue by clement30** [pavelpasha/s63lib#6]
HI sir, 
Your work is what I'm looking for!

But I don't know how to compile this projet... I use vs code with linux and I downloaded a c++ compiler

Can you tell me how to compile your project with vs, please ?

Thank you very much for your work and I am looking forward to hearing from you !

**Comment by pavelpasha** [comment]
Hi. I am use  MSVC compiler on Windows. I tried compile it with GCC on Linux and faced with lot of errors. So i fixed it, and now it should be compatible with gcc. Please try it again.

**Comment by clement30** [comment]
Hi, I use this command to compile :  gcc -g  *.cpp zlib/*.c -o build.out, but I have always few errors...

Can you tell me how you compile it with gcc and how to use your project please ?
Thank you very much !
